# -*- coding: utf-8 -*-
"""lat_long.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Skp4YvHesgkIjyEiqnRegxB7JNngKPCl
"""

print('location')

