# Generated by Django 3.1.2 on 2020-10-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('hash_id', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
