# Generated by Django 3.1.2 on 2020-10-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='id',
            new_name='num',
        ),
    ]
